### ISSUE TITLE
Losing colour profiles

### ISSUE THREAD

**Issue by cakehurst** [ImageOptim/ImageOptim#179]
I seem to be getting some inconsistent results when compressing pngs and trying to keep the colour profile. 

Mac OSX 10.11.5
Image Optim 1.6.4

These are my prefs
![screen shot 2016-12-19 at 19 56 10](https://cloud.githubusercontent.com/assets/24659145/21327057/38d498f4-c625-11e6-9343-22758c5a6012.png)

I'm then checking the results with http://metapicz.com/ which is showing no profiles included.

**Comment by pornel** [comment]
Thanks. Fixed in d5e7a94127355026a985cfbad7fec13b6ef6a5b1

BTW: you really shouldn't use color profiles, as they reduce color quality and bloat the files.

**Comment by cakehurst** [comment]
Thanks for the fix. How exactly to I pull and install that version? 

The profiles are a client request. Otherwise the colours go crazy on newer iMac and MBPs

**Comment by cakehurst** [comment]
@pornel Just trying to embed some more colour profiles into pngs and this bug still seems to be present. Did the fix get included in the latest version? 1.7?
